apiVersion: apps/v1
kind: Deployment
metadata:
  name: easyclaim-frontend-dev
  namespace: development
  labels:
    name: easyclaim-frontend-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      name: easyclaim-frontend-pod-dev
  strategy:
    type: Recreate
  template:
    metadata:
      name: easyclaim-frontend-pod-dev
      labels:
        name: easyclaim-frontend-pod-dev
    spec:
      containers:
        - name:  easyclaim-frontend-dev
          image: vigneshsweekaran/easyclaim-frontend-dev:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: easyclaim-frontend-service-dev
  namespace: development
  labels:
    name: easyclaim-frontend-service-dev
spec:
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 32001
  selector:
    name: easyclaim-frontend-pod
  type: NodePort
